// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6ixDHramBEqGxNPppwE4dWEgRW8x67OU',
    appId: '1:1001498532666:web:15481d6c88cf6deb074e03',
    messagingSenderId: '1001498532666',
    projectId: 'prm001-bf36b',
    authDomain: 'prm001-bf36b.firebaseapp.com',
    storageBucket: 'prm001-bf36b.firebasestorage.app',
    measurementId: 'G-CQ2EKEBT8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtgzPtoBZ5UZet3TBbZoyDvaTOM2kgMxM',
    appId: '1:1001498532666:android:47c54e49dd2473bd074e03',
    messagingSenderId: '1001498532666',
    projectId: 'prm001-bf36b',
    storageBucket: 'prm001-bf36b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGUjPY1p0d4JW4AuVsA9xcbrQfIPqz99Y',
    appId: '1:1001498532666:ios:023e79ad88481880074e03',
    messagingSenderId: '1001498532666',
    projectId: 'prm001-bf36b',
    storageBucket: 'prm001-bf36b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGUjPY1p0d4JW4AuVsA9xcbrQfIPqz99Y',
    appId: '1:1001498532666:ios:023e79ad88481880074e03',
    messagingSenderId: '1001498532666',
    projectId: 'prm001-bf36b',
    storageBucket: 'prm001-bf36b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6ixDHramBEqGxNPppwE4dWEgRW8x67OU',
    appId: '1:1001498532666:web:9a6cf595e791f0f9074e03',
    messagingSenderId: '1001498532666',
    projectId: 'prm001-bf36b',
    authDomain: 'prm001-bf36b.firebaseapp.com',
    storageBucket: 'prm001-bf36b.firebasestorage.app',
    measurementId: 'G-9E1H25MXGM',
  );
}
