// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNBmkAwrgspz6UnbPz3N_jejNa1Qx5A_8',
    appId: '1:654400133150:web:593038f1bd1294dd69f60f',
    messagingSenderId: '654400133150',
    projectId: 'prm01315',
    authDomain: 'prm01315.firebaseapp.com',
    storageBucket: 'prm01315.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8lM3u9yNCD7o4UIFAmjHgyGshbaVX0_c',
    appId: '1:654400133150:android:4c10e2d2cc03b30f69f60f',
    messagingSenderId: '654400133150',
    projectId: 'prm01315',
    storageBucket: 'prm01315.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjtBK4S2anw3xAW-rlCofjqV_8zVRGx0Y',
    appId: '1:654400133150:ios:623d5931d9da5d9069f60f',
    messagingSenderId: '654400133150',
    projectId: 'prm01315',
    storageBucket: 'prm01315.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjtBK4S2anw3xAW-rlCofjqV_8zVRGx0Y',
    appId: '1:654400133150:ios:623d5931d9da5d9069f60f',
    messagingSenderId: '654400133150',
    projectId: 'prm01315',
    storageBucket: 'prm01315.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNBmkAwrgspz6UnbPz3N_jejNa1Qx5A_8',
    appId: '1:654400133150:web:034520fd00c865bb69f60f',
    messagingSenderId: '654400133150',
    projectId: 'prm01315',
    authDomain: 'prm01315.firebaseapp.com',
    storageBucket: 'prm01315.firebasestorage.app',
  );
}
